name: cel-cnv-eacon
channels:
  - bioconda
  - r
  - conda-forge
  - defaults
dependencies:
  - r-devtools ==1.13.6
  - ascat ==2.5.1
  - cnv_facets ==0.14.0
  - bioconductor-affxparser ==1.56.0
  - bioconductor-biostrings ==2.50.2
  - bioconductor-aroma.light ==3.14.0
  - bioconductor-bsgenome ==1.50.0
  - bioconductor-bsgenome.hsapiens.ucsc.hg19 ==1.4.0
  - bioconductor-bsgenome.hsapiens.ucsc.hg38 ==1.4.1
  - bioconductor-copynumber ==1.22.0
  - bioconductor-genomicranges ==1.34.0
  - bioconductor-limma ==3.40.0
  - bioconductor-rhdf5 ==2.28.0
  - r-sequenza ==3.0.0
  - python ==3.7
  - datrie ==0.7.1
  - git ==2.20.1
  - pip ==19.1.1
  - pip:
    - snakemake ==5.5.0
